spring:
  application:
    name: tipjs-course
  datasource:
    url: jdbc:...
    username: <username>
    password: <password>
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8080

